alter table repairment.hinhyeucau drop foreign key FKnxqdamrf9qi6fvlje75y192hj;
alter table repairment.hinhyeucau drop foreign key FK70184iusa39ssjwrrggkyh5d2;
alter table repairment.yeucau drop foreign key FKg8vnur1m54ag1axm12299y2jn;
alter table repairment.yeucau drop foreign key FKr6e0sjpnmxfnl3aualt70xsei;
drop table if exists repairment.dichvucungcap;
drop table if exists repairment.hinhyeucau;
drop table if exists repairment.khachhang;
drop table if exists repairment.yeucau;
create table repairment.dichvucungcap (MADVCC integer not null auto_increment, TENDV longtext, primary key (MADVCC));
create table repairment.hinhyeucau (MAHINHYC integer not null auto_increment, hinh_yc1 tinyblob, hinh_yc1_64bit varchar(255), hinh_yc2 tinyblob, hinh_yc2_64bit varchar(255), MADVCC integer not null, MAYEUCAU integer not null, primary key (MAHINHYC));
create table repairment.khachhang (MAKH integer not null auto_increment, EMAIL varchar(100), HINH mediumblob, HINH_64 longtext, MATKHAU varchar(100), SDT varchar(100), TENNGUOIDUNG varchar(100), primary key (MAKH));
create table repairment.yeucau (MAYEUCAU integer not null auto_increment, DIACHI varchar(100), GHICHU varchar(100), NGAYYEUCAU varchar(100), TINHTRANG varchar(100), MADVCC integer not null, MAKH integer not null, primary key (MAYEUCAU));
alter table repairment.hinhyeucau add constraint FKnxqdamrf9qi6fvlje75y192hj foreign key (MADVCC) references repairment.dichvucungcap (MADVCC);
alter table repairment.hinhyeucau add constraint FK70184iusa39ssjwrrggkyh5d2 foreign key (MAYEUCAU) references repairment.yeucau (MAYEUCAU);
alter table repairment.yeucau add constraint FKg8vnur1m54ag1axm12299y2jn foreign key (MADVCC) references repairment.dichvucungcap (MADVCC);
alter table repairment.yeucau add constraint FKr6e0sjpnmxfnl3aualt70xsei foreign key (MAKH) references repairment.khachhang (MAKH);
alter table repairment.hinhyeucau drop foreign key FKnxqdamrf9qi6fvlje75y192hj;
alter table repairment.hinhyeucau drop foreign key FK70184iusa39ssjwrrggkyh5d2;
alter table repairment.yeucau drop foreign key FKg8vnur1m54ag1axm12299y2jn;
alter table repairment.yeucau drop foreign key FKr6e0sjpnmxfnl3aualt70xsei;
drop table if exists repairment.dichvucungcap;
drop table if exists repairment.hinhyeucau;
drop table if exists repairment.khachhang;
drop table if exists repairment.yeucau;
create table repairment.dichvucungcap (MADVCC integer not null auto_increment, TENDV longtext, primary key (MADVCC));
create table repairment.hinhyeucau (MAHINHYC integer not null auto_increment, hinh_yc1 tinyblob, hinh_yc1_64bit varchar(255), hinh_yc2 tinyblob, hinh_yc2_64bit varchar(255), MADVCC integer not null, MAYEUCAU integer not null, primary key (MAHINHYC));
create table repairment.khachhang (MAKH integer not null auto_increment, EMAIL varchar(100), HINH mediumblob, HINH_64 longtext, MATKHAU varchar(100), SDT varchar(100), TENNGUOIDUNG varchar(100), primary key (MAKH));
create table repairment.yeucau (MAYEUCAU integer not null auto_increment, DIACHI varchar(100), GHICHU varchar(100), NGAYYEUCAU varchar(100), TINHTRANG varchar(100), MADVCC integer not null, MAKH integer not null, primary key (MAYEUCAU));
alter table repairment.hinhyeucau add constraint FKnxqdamrf9qi6fvlje75y192hj foreign key (MADVCC) references repairment.dichvucungcap (MADVCC);
alter table repairment.hinhyeucau add constraint FK70184iusa39ssjwrrggkyh5d2 foreign key (MAYEUCAU) references repairment.yeucau (MAYEUCAU);
alter table repairment.yeucau add constraint FKg8vnur1m54ag1axm12299y2jn foreign key (MADVCC) references repairment.dichvucungcap (MADVCC);
alter table repairment.yeucau add constraint FKr6e0sjpnmxfnl3aualt70xsei foreign key (MAKH) references repairment.khachhang (MAKH);
alter table repairment.hinhyeucau drop foreign key FKnxqdamrf9qi6fvlje75y192hj;
alter table repairment.hinhyeucau drop foreign key FK70184iusa39ssjwrrggkyh5d2;
alter table repairment.yeucau drop foreign key FKg8vnur1m54ag1axm12299y2jn;
alter table repairment.yeucau drop foreign key FKr6e0sjpnmxfnl3aualt70xsei;
drop table if exists repairment.dichvucungcap;
drop table if exists repairment.hinhyeucau;
drop table if exists repairment.khachhang;
drop table if exists repairment.yeucau;
create table repairment.dichvucungcap (MADVCC integer not null auto_increment, TENDV longtext, primary key (MADVCC));
create table repairment.hinhyeucau (MAHINHYC integer not null auto_increment, hinh_yc1 tinyblob, hinh_yc1_64bit varchar(255), hinh_yc2 tinyblob, hinh_yc2_64bit varchar(255), MADVCC integer not null, MAYEUCAU integer not null, primary key (MAHINHYC));
create table repairment.khachhang (MAKH integer not null auto_increment, EMAIL varchar(100), HINH mediumblob, HINH_64 longtext, MATKHAU varchar(100), SDT varchar(100), TENNGUOIDUNG varchar(100), primary key (MAKH));
create table repairment.yeucau (MAYEUCAU integer not null auto_increment, DIACHI varchar(100), GHICHU varchar(100), NGAYYEUCAU varchar(100), TINHTRANG varchar(100), MADVCC integer not null, MAKH integer not null, primary key (MAYEUCAU));
alter table repairment.hinhyeucau add constraint FKnxqdamrf9qi6fvlje75y192hj foreign key (MADVCC) references repairment.dichvucungcap (MADVCC);
alter table repairment.hinhyeucau add constraint FK70184iusa39ssjwrrggkyh5d2 foreign key (MAYEUCAU) references repairment.yeucau (MAYEUCAU);
alter table repairment.yeucau add constraint FKg8vnur1m54ag1axm12299y2jn foreign key (MADVCC) references repairment.dichvucungcap (MADVCC);
alter table repairment.yeucau add constraint FKr6e0sjpnmxfnl3aualt70xsei foreign key (MAKH) references repairment.khachhang (MAKH);
alter table repairment.hinhyeucau drop foreign key FKnxqdamrf9qi6fvlje75y192hj;
alter table repairment.hinhyeucau drop foreign key FK70184iusa39ssjwrrggkyh5d2;
alter table repairment.yeucau drop foreign key FKg8vnur1m54ag1axm12299y2jn;
alter table repairment.yeucau drop foreign key FKr6e0sjpnmxfnl3aualt70xsei;
drop table if exists repairment.dichvucungcap;
drop table if exists repairment.hinhyeucau;
drop table if exists repairment.khachhang;
drop table if exists repairment.yeucau;
create table repairment.dichvucungcap (MADVCC integer not null auto_increment, TENDV longtext, primary key (MADVCC));
create table repairment.hinhyeucau (MAHINHYC integer not null auto_increment, hinh_yc1 tinyblob, hinh_yc1_64bit varchar(255), hinh_yc2 tinyblob, hinh_yc2_64bit varchar(255), MADVCC integer not null, MAYEUCAU integer not null, primary key (MAHINHYC));
create table repairment.khachhang (MAKH integer not null auto_increment, EMAIL varchar(100), HINH mediumblob, HINH_64 longtext, MATKHAU varchar(100), SDT varchar(100), TENNGUOIDUNG varchar(100), primary key (MAKH));
create table repairment.yeucau (MAYEUCAU integer not null auto_increment, DIACHI varchar(100), GHICHU varchar(100), NGAYYEUCAU varchar(100), TINHTRANG varchar(100), MADVCC integer not null, MAKH integer not null, primary key (MAYEUCAU));
alter table repairment.hinhyeucau add constraint FKnxqdamrf9qi6fvlje75y192hj foreign key (MADVCC) references repairment.dichvucungcap (MADVCC);
alter table repairment.hinhyeucau add constraint FK70184iusa39ssjwrrggkyh5d2 foreign key (MAYEUCAU) references repairment.yeucau (MAYEUCAU);
alter table repairment.yeucau add constraint FKg8vnur1m54ag1axm12299y2jn foreign key (MADVCC) references repairment.dichvucungcap (MADVCC);
alter table repairment.yeucau add constraint FKr6e0sjpnmxfnl3aualt70xsei foreign key (MAKH) references repairment.khachhang (MAKH);
